# Generated by Django 2.2.2 on 2019-06-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.CharField(choices=[('f', 'friend'), ('a', 'acqaintance'), ('c', 'celebrity')], max_length=1),
        ),
    ]
