# Generated by Django 2.2.2 on 2019-06-24 08:12

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20190624_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, default=123, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
